name: '🤝 Ubuntu Rocks - Member Onboarding'
description: Become a contributing member of the Rocks Community
title: "[onboarding] <replace by your name/username>"
labels: ["onboarding"]
projects: ["ubuntu-rocks/2"]
body:
  - type: markdown
    attributes:
      value: |
        👋 Welcome! Thank you for wanting to participate in the Ubuntu Rocks community playground. This issue will guide you through the onboarding process.
  - type: textarea
    id: introduction
    attributes:
      label: 🚀 Introduction
      description: |
        Briefly introduce yourself. There's no need to share any private data...we're just
        looking to know more about you, your background and your motivation to join this project.

        Feel free to drop references for your personal website and social media pages.
    validations:
      required: false
  - type: input
    id: repos
    attributes:
      label: 🔑 Repositories
      description: A comma-separated list of repositories you'd like to create or get access to. Leave empty if the repository where you are creating the issue is the only one you need access to.
    validations:
      required: false
  - type: input
    id: matrix
    attributes:
      label: 💬 Matrix username
      description: What is your Matrix username in the [Rocks Community space](https://matrix.to/#/#rocks:ubuntu.com)?
      placeholder: ex. johndoe
    validations:
      required: true
  - type: checkboxes
    id: contributor-agreement
    attributes:
      label: Canonical contributor licence agreement
      description: This playground is a shared space, and even though you **don't need to sign** the contributor agreement, we'd like to ask you to become familiar with it anyway.
      options:
        - label: I have read [Canonical's contributor licence agreement](https://ubuntu.com/legal/contributors)
          required: true  
  - type: checkboxes
    id: coc
    attributes:
      label: Ubuntu Code of Conduct
      description: This GitHub playground is still part of the Rocks Community, and thus shall abide by the Ubuntu CoC.
      options:
        - label: I have read [Ubuntu Code of Conduct](https://ubuntu.com/community/ethos/code-of-conduct)
          required: true
